import type { Game } from "./ProductCard";

export const allGames: Game[] = [
  // PS5
  {
  id: 1,
  title: "God of War Ragnarök",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 44990,
  originalPrice: 74990,
  discount: 40,
  image: "/games/god-of-war-ragnarok.jpg",  
  genre: "Acción",
  stock: 14,
  rating: 4.9,
  reviews: 3842,
  description: "Kratos y Atreus enfrentan el inicio del Ragnarök en una aventura cargada de combates, mitología nórdica y decisiones familiares difíciles.",
  developer: "Santa Monica Studio",
  releaseYear: 2022,
},
{
  id: 2,
  title: "Returnal",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 32990,
  originalPrice: 59990,
  discount: 45,
image: "/games/returnal.jpg",  genre: "Acción",
  stock: 18,
  rating: 4.6,
  reviews: 142,
  description: "Shooter de ciencia ficción con exploración, acción intensa y ciclos temporales en un planeta alienígena hostil.",
  developer: "Housemarque",
  releaseYear: 2021,
},
{
  id: 3,
  title: "Horizon Forbidden West",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 39990,
  originalPrice: 64990,
  discount: 38,
  image: "/games/horizon-forbidden-west.jpg",
  genre: "Aventura",
  stock: 54,
  rating: 4.7,
  reviews: 189,
  description: "Aloy viaja al Oeste Prohibido para descubrir nuevas amenazas, enfrentar máquinas gigantes y salvar un mundo al borde del colapso.",
  developer: "Guerrilla Games",
  releaseYear: 2022,
},
{
  id: 4,
  title: "Final Fantasy XVI",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 48990,
  image: "/games/final-fantasy-xvi.jpg",
  genre: "RPG",
  stock: 8,
  rating: 4.7,
  reviews: 120,
  description: "RPG de acción con batallas espectaculares, invocaciones gigantes y una historia oscura ambientada en el mundo de Valisthea.",
  developer: "Square Enix Creative Business Unit III",
  releaseYear: 2023,
},
  // PS4
  {
  id: 5,
  title: "Call of Duty: Modern Warfare II",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 31155,
  originalPrice: 54900,
  discount: 43,
  image: "/games/call-of-duty-black-ops-7.jpg",  
  genre: "Shooter",
  stock: 0,
  rating: 4.8,
  reviews: 228,
  description: "Experimentá una intensa campaña militar y un competitivo modo multijugador con gráficos de última generación y combates frenéticos.",
  developer: "Infinity Ward",
  releaseYear: 2022,
},
{
  id: 6,
  title: "Red Dead Redemption 2",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 18990,
  originalPrice: 48990,
  discount: 61,
  image: "/games/red-dead-redemption-2.jpg",
  genre: "Aventura",
  stock: 10,
  rating: 4.9,
  reviews: 1542,
  description: "Viví la historia de Arthur Morgan en un enorme mundo abierto ambientado en el ocaso del Viejo Oeste, con una narrativa considerada entre las mejores de la industria.",
  developer: "Rockstar Games",
  releaseYear: 2018,
},
{
  id: 7,
  title: "Grand Theft Auto V",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 14990,
  originalPrice: 35990,
  discount: 58,
  image: "/games/gta-v.jpg",  
  genre: "Acción",
  stock: 18,
  rating: 4.8,
  reviews: 2875,
  description: "Alterná entre Michael, Franklin y Trevor mientras explorás Los Santos en una aventura repleta de acción, misiones y libertad total.",
  developer: "Rockstar North",
  releaseYear: 2014,
},
{
  id: 8,
  title: "Resident Evil 4 Remake",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 29990,
  originalPrice: 54990,
  discount: 45,
  image: "/games/resident-evil-4-remake.jpg", 
  genre: "Terror",
  stock: 15,
  rating: 4.8,
  reviews: 612,
  description: "Leon S. Kennedy regresa para rescatar a la hija del presidente en una reinvención moderna del clásico survival horror.",
  developer: "Capcom",
  releaseYear: 2023,
},
  // Xbox
  {
  id: 9,
  title: "Microsoft Flight Simulator",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 38990,
  originalPrice: 64990,
  discount: 40,
image: "/games/microsoft-flight-simulator.jpg",  
genre: "Simulación",
  stock: 0,
  rating: 4.7,
  reviews: 100,
  description: "Simulador de vuelo realista con aviones detallados, clima dinámico y escenarios basados en ubicaciones reales del mundo.",
  developer: "Asobo Studio",
  releaseYear: 2021,
},
{
  id: 10,
  title: "Ori and the Will of the Wisps",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 18990,
  originalPrice: 34990,
  discount: 46,
image: "/games/ori-and-the-will-of-the-wisps.jpg",  
genre: "Plataformas",
  stock: 22,
  rating: 4.9,
  reviews: 100,
  description: "Aventura de plataformas con una dirección artística hermosa, exploración metroidvania y una historia emotiva.",
  developer: "Moon Studios",
  releaseYear: 2020,
},
{
  id: 11,
  title: "Psychonauts 2",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 24990,
  originalPrice: 44990,
  discount: 44,
image: "/games/psychonauts-2.jpg",
  genre: "Aventura",
  stock: 0,
  rating: 4.7,
  reviews: 100,
  description: "Aventura de plataformas creativa donde Raz explora mundos mentales llenos de humor, imaginación y desafíos únicos.",
  developer: "Double Fine Productions",
  releaseYear: 2021,
},
{
  id: 12,
  title: "State of Decay 2",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 19990,
  originalPrice: 39990,
  discount: 50,
image: "/games/state-of-decay-2.jpg",
  genre: "Supervivencia",
  stock: 2,
  rating: 4.4,
  reviews: 100,
  description: "Juego de supervivencia en mundo abierto donde administrás una comunidad, buscás recursos y enfrentás amenazas constantes.",
  developer: "Undead Labs",
  releaseYear: 2018,
},
  // Nintendo
  {
  id: 13,
  title: "Luigi's Mansion 3",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 44990,
  originalPrice: 64990,
  discount: 31,
image: "/games/luigis-mansion-3.jpg",
  genre: "Aventura",
  stock: 1,
  rating: 4.8,
  reviews: 100,
  description: "Acompañá a Luigi en una divertida aventura dentro de un hotel embrujado resolviendo acertijos y capturando fantasmas con la Succionaentes G-00.",
  developer: "Next Level Games",
  releaseYear: 2019,
},
{
  id: 14,
  title: "Fire Emblem Engage",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 47990,
  originalPrice: 67990,
  discount: 29,
image: "/games/fire-emblem-engage.jpg",
  genre: "RPG táctico",
  stock: 1,
  rating: 4.7,
  reviews: 100,
  description: "RPG estratégico por turnos donde invocás héroes legendarios para librar batallas y proteger el continente de Elyos.",
  developer: "Intelligent Systems",
  releaseYear: 2023,
},
{
  id: 15,
  title: "Kirby and the Forgotten Land",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 38990,
  originalPrice: 56990,
  discount: 32,
  image: "/games/kirby-and-the-forgotten-land.jpg",
  genre: "Plataformas",
  stock: 24,
  rating: 4.8,
  reviews: 100,
  description: "Kirby explora un misterioso mundo abandonado utilizando sus clásicas habilidades de copia y nuevas transformaciones para rescatar a los Waddle Dee.",
  developer: "HAL Laboratory",
  releaseYear: 2022,
},
{
  id: 16,
  title: "Splatoon 3",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 42990,
  originalPrice: 62990,
  discount: 32,
image: "/games/splatoon-3.jpg",
  genre: "Shooter",
  stock: 16,
  rating: 4.7,
  reviews: 100,
  description: "Shooter competitivo donde dos equipos luchan por cubrir el escenario con tinta mientras utilizan armas y habilidades únicas.",
  developer: "Nintendo EPD",
  releaseYear: 2022,
},
  // Sega
  {
  id: 17,
  title: "Sonic Origins Plus",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 22990,
  originalPrice: 44990,
  discount: 49,
image: "/games/sonic-origins-plus.jpg",
  genre: "Plataformas",
  stock: 12,
  rating: 4.5,
  reviews: 100,
  description: "Colección que reúne los clásicos Sonic the Hedgehog remasterizados, con nuevos personajes, modos de juego y contenido adicional.",
  developer: "Sonic Team",
  releaseYear: 2023,
},
{
  id: 18,
  title: "Two Point Campus",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 19990,
  originalPrice: 39990,
  discount: 50,
image: "/games/two-point-campus.jpg",
  genre: "Simulación",
  stock: 27,
  rating: 4.6,
  reviews: 100,
  description: "Creá y administrá tu propia universidad diseñando edificios, contratando profesores y guiando a los estudiantes hacia el éxito.",
  developer: "Two Point Studios",
  releaseYear: 2022,
},
{
  id: 19,
  title: "Humankind",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 24990,
  originalPrice: 49990,
  discount: 50,
image: "/games/humankind.jpg",
  genre: "Estrategia",
  stock: 21,
  rating: 4.4,
  reviews: 152,
  description: "Juego de estrategia por turnos donde construís una civilización combinando culturas históricas y tomando decisiones que cambian el curso de la humanidad.",
  developer: "Amplitude Studios",
  releaseYear: 2021,
},
{
  id: 20,
  title: "Judgment",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 16990,
  originalPrice: 34990,
  discount: 51,
image: "/games/judgment.jpg",
  genre: "Acción",
  stock: 2,
  rating: 4.8,
  reviews: 80,
  description: "Controlá al detective Takayuki Yagami mientras investiga una serie de asesinatos en Kamurocho combinando exploración, combates y trabajo detectivesco.",
  developer: "Ryu Ga Gotoku Studio",
  releaseYear: 2018,
},
  {
  id: 21,
  title: "Marvel's Spider-Man 2",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 52990,
  originalPrice: 74990,
  discount: 29,
  image: "/games/spider-man-2.jpg",
  genre: "Acción",
  stock: 18,
  rating: 4.9,
  reviews: 132,
  description: "Aventura de acción en mundo abierto protagonizada por Peter Parker y Miles Morales enfrentando nuevas amenazas en Nueva York.",
  developer: "Insomniac Games",
  releaseYear: 2023,
},
{
  id: 22,
  title: "The Last of Us Part II",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 34990,
  originalPrice: 59990,
  discount: 42,
image: "/games/the-last-of-us-part-ii.jpg",
  genre: "Aventura",
  stock: 14,
  rating: 4.8,
  reviews: 210,
  description: "Historia intensa de supervivencia, exploración y combate en un mundo postapocalíptico.",
  developer: "Naughty Dog",
  releaseYear: 2020,
},
{
  id: 23,
  title: "Halo Infinite",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 29990,
  originalPrice: 49990,
  discount: 40,
image: "/games/halo-infinite.jpg",
  genre: "Shooter",
  stock: 20,
  rating: 4.5,
  reviews: 98,
  description: "Nueva campaña del Jefe Maestro con combates futuristas, exploración abierta y multijugador competitivo.",
  developer: "343 Industries",
  releaseYear: 2021,
},
{
  id: 24,
  title: "Forza Horizon 5",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 42990,
  originalPrice: 64990,
  discount: 34,
image: "/games/forza-horizon-5.jpg",
  genre: "Carreras",
  stock: 2,
  rating: 4.9,
  reviews: 156,
  description: "Juego de conducción en mundo abierto ambientado en México, con cientos de autos y eventos dinámicos.",
  developer: "Playground Games",
  releaseYear: 2021,
},
{
  id: 25,
  title: "Super Mario Odyssey",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 44990,
  originalPrice: 69990,
  discount: 36,
image: "/games/super-mario-odyssey.jpg",
  genre: "Plataformas",
  stock: 16,
  rating: 4.9,
  reviews: 180,
  description: "Aventura de plataformas donde Mario viaja por distintos reinos usando nuevas habilidades junto a Cappy.",
  developer: "Nintendo",
  releaseYear: 2017,
},
{
  id: 26,
  title: "The Legend of Zelda: Tears of the Kingdom",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 58990,
  originalPrice: 79990,
  discount: 26,
image: "/games/zelda-tears-of-the-kingdom.jpg",
  genre: "Aventura",
  stock: 19,
  rating: 5.0,
  reviews: 240,
  description: "Aventura épica de exploración, construcción y combate en Hyrule y sus nuevas islas flotantes.",
  developer: "Nintendo",
  releaseYear: 2023,
},
{
  id: 27,
  title: "Persona 5 Royal",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 24990,
  originalPrice: 49990,
  discount: 50,
image: "/games/persona-5-royal.jpg",
  genre: "RPG",
  stock: 22,
  rating: 4.9,
  reviews: 145,
  description: "RPG japonés con combates por turnos, vida escolar, vínculos sociales y una historia estilizada.",
  developer: "Atlus",
  releaseYear: 2019,
},
{
  id: 28,
  title: "Like a Dragon: Infinite Wealth",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 53990,
  originalPrice: 74990,
  discount: 28,
image: "/games/like-a-dragon-infinite-wealth.jpg",  
genre: "RPG",
  stock: 12,
  rating: 4.7,
  reviews: 89,
  description: "RPG narrativo con combates por turnos, humor, drama criminal y exploración en Japón y Hawái.",
  developer: "Ryu Ga Gotoku Studio",
  releaseYear: 2024,
},
{
  id: 29,
  title: "Demon's Souls",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 46990,
  originalPrice: 69990,
  discount: 33,
image: "/games/demons-souls.jpg",
  genre: "RPG",
  stock: 4,
  rating: 4.8,
  reviews: 104,
  description: "Remake del clásico RPG de acción desafiante, con combates exigentes y ambientación oscura.",
  developer: "Bluepoint Games",
  releaseYear: 2020,
},
{
  id: 30,
  title: "Ghost of Tsushima",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 38990,
  originalPrice: 64990,
  discount: 40,
image: "/games/ghost-of-tsushima.jpg",
  genre: "Acción",
  stock: 0,
  rating: 4.8,
  reviews: 167,
  description: "Aventura samurái en mundo abierto ambientada en la isla de Tsushima durante la invasión mongola.",
  developer: "Sucker Punch Productions",
  releaseYear: 2020,
},
{
  id: 31,
  title: "Gears 5",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 26990,
  originalPrice: 44990,
  discount: 40,
image: "/games/gears-5.jpg",
  genre: "Shooter",
  stock: 21,
  rating: 4.5,
  reviews: 92,
  description: "Shooter en tercera persona con campaña cinematográfica, cooperativo y combates intensos.",
  developer: "The Coalition",
  releaseYear: 2019,
},
{
  id: 32,
  title: "Starfield",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 49990,
  originalPrice: 69990,
  discount: 29,
image: "/games/starfield.jpg",
  genre: "RPG",
  stock: 13,
  rating: 4.3,
  reviews: 120,
  description: "RPG espacial de exploración, misiones, personalización de naves y viajes entre sistemas planetarios.",
  developer: "Bethesda Game Studios",
  releaseYear: 2023,
},
{
  id: 33,
  title: "Mario Kart 8 Deluxe",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 42990,
  originalPrice: 64990,
  discount: 34,
image: "/games/mario-kart-8-deluxe.jpg",
  genre: "Carreras",
  stock: 2,
  rating: 4.9,
  reviews: 230,
  description: "Juego de carreras arcade con personajes de Nintendo, circuitos variados y multijugador local u online.",
  developer: "Nintendo",
  releaseYear: 2017,
},
{
  id: 34,
  title: "Animal Crossing: New Horizons",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 39990,
  originalPrice: 59990,
  discount: 33,
image: "/games/animal-crossing-new-horizons.jpg",
  genre: "Simulación",
  stock: 15,
  rating: 4.8,
  reviews: 175,
  description: "Simulador relajado donde construís y decorás tu isla mientras interactuás con vecinos animales.",
  developer: "Nintendo",
  releaseYear: 2020,
},
{
  id: 35,
  title: "Sonic Superstars",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 28990,
  originalPrice: 52990,
  discount: 45,
image: "/games/sonic-superstars.jpg",
  genre: "Plataformas",
  stock: 18,
  rating: 4.2,
  reviews: 76,
  description: "Aventura de plataformas 2D con Sonic y sus amigos, niveles coloridos y habilidades clásicas renovadas.",
  developer: "Arzest / Sonic Team",
  releaseYear: 2023,
},
{
  id: 36,
  title: "Football Manager 2024",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 31990,
  originalPrice: 49990,
  discount: 36,
image: "/games/football-manager-2024.jpg",
  genre: "Deportes",
  stock: 20,
  rating: 4.6,
  reviews: 88,
  description: "Simulador de gestión futbolística con tácticas, fichajes, desarrollo de plantel y competiciones reales.",
  developer: "Sports Interactive",
  releaseYear: 2023,
},
{
  id: 37,
  title: "Ratchet & Clank: Rift Apart",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 43990,
  originalPrice: 69990,
  discount: 37,
image: "/games/ratchet-and-clank-rift-apart.jpg",
  genre: "Aventura",
  stock: 1,
  rating: 4.7,
  reviews: 112,
  description: "Aventura de acción con portales dimensionales, armas creativas y escenarios coloridos de nueva generación.",
  developer: "Insomniac Games",
  releaseYear: 2021,
},
{
  id: 38,
  title: "Uncharted 4: A Thief's End",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 24990,
  originalPrice: 44990,
  discount: 44,
image: "/games/uncharted-4-a-thiefs-end.jpg",
  genre: "Aventura",
  stock: 23,
  rating: 4.8,
  reviews: 190,
  description: "Aventura cinematográfica de Nathan Drake con exploración, tiroteos, puzles y grandes escenas de acción.",
  developer: "Naughty Dog",
  releaseYear: 2016,
},
{
  id: 39,
  title: "Sea of Thieves",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 27990,
  originalPrice: 49990,
  discount: 44,
image: "/games/sea-of-thieves.jpg",
  genre: "Aventura",
  stock: 0,
  rating: 4.4,
  reviews: 101,
  description: "Aventura multijugador de piratas con exploración, barcos, tesoros, combates navales y eventos cooperativos.",
  developer: "Rare",
  releaseYear: 2018,
},
{
  id: 40,
  title: "Metroid Dread",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 37990,
  originalPrice: 59990,
  discount: 37,
image: "/games/metroid-dread.jpg",
  genre: "Acción",
  stock: 14,
  rating: 4.7,
  reviews: 130,
  description: "Aventura de acción y exploración lateral con Samus Aran, enemigos desafiantes y diseño metroidvania.",
  developer: "MercurySteam / Nintendo",
  releaseYear: 2021,
},
{
  id: 41,
  title: "Grand Theft Auto IV",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 14990,
  originalPrice: 29990,
  discount: 50,
image: "/games/grand-theft-auto-iv.jpg",
  genre: "Acción",
  stock: 1,
  rating: 4.8,
  reviews: 215,
  description: "Viví la historia de Niko Bellic en Liberty City con un mundo abierto lleno de misiones, acción y exploración.",
  developer: "Rockstar North",
  releaseYear: 2008,
},
{
  id: 42,
  title: "Red Dead Redemption",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 16990,
  originalPrice: 34990,
  discount: 51,
image: "/games/red-dead-redemption.jpg",
  genre: "Acción",
  stock: 18,
  rating: 4.9,
  reviews: 198,
  description: "Aventura en el Lejano Oeste protagonizada por John Marston, combinando exploración, disparos y una historia inolvidable.",
  developer: "Rockstar San Diego",
  releaseYear: 2010,
},
{
  id: 43,
  title: "The Elder Scrolls V: Skyrim",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 18990,
  originalPrice: 35990,
  discount: 47,
image: "/games/the-elder-scrolls-v-skyrim.jpg",
  genre: "RPG",
  stock: 21,
  rating: 5.0,
  reviews: 320,
  description: "Explorá un enorme mundo abierto lleno de dragones, magia, mazmorras y cientos de misiones.",
  developer: "Bethesda Game Studios",
  releaseYear: 2011,
},
{
  id: 44,
  title: "Metal Gear Solid 4: Guns of the Patriots",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 17990,
  originalPrice: 33990,
  discount: 47,
image: "/games/metal-gear-solid-4-guns-of-the-patriots.jpg",
  genre: "Sigilo",
  stock: 10,
  rating: 4.9,
  reviews: 172,
  description: "Solid Snake enfrenta su última misión en una aventura repleta de infiltración, estrategia y narrativa cinematográfica.",
  developer: "Kojima Productions",
  releaseYear: 2008,
},
{
  id: 45,
  title: "Super Mario Galaxy",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 19990,
  originalPrice: 39990,
  discount: 50,
image: "/games/super-mario-galaxy.jpg",
  genre: "Plataformas",
  stock: 17,
  rating: 4.9,
  reviews: 205,
  description: "Mario viaja por galaxias llenas de desafíos utilizando nuevas mecánicas de gravedad y exploración.",
  developer: "Nintendo",
  releaseYear: 2007,
},
{
  id: 46,
  title: "Sonic Generations",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 15990,
  originalPrice: 29990,
  discount: 47,
image: "/games/sonic-generations.jpg",
  genre: "Plataformas",
  stock: 24,
  rating: 4.6,
  reviews: 126,
  description: "Reuní al Sonic clásico y moderno en una celebración de la historia de la saga con niveles remasterizados.",
  developer: "Sonic Team",
  releaseYear: 2011,
},
{
  id: 47,
  title: "Halo 3",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 13990,
  originalPrice: 28990,
  discount: 52,
image: "/games/halo-3.jpg",
  genre: "Shooter",
  stock: 28,
  rating: 4.8,
  reviews: 240,
  description: "El Jefe Maestro regresa para finalizar la trilogía original en uno de los shooters más influyentes de la historia.",
  developer: "Bungie",
  releaseYear: 2007,
},
{
  id: 48,
  title: "God of War III",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 16990,
  originalPrice: 32990,
  discount: 48,
image: "/games/god-of-war-iii.jpg",
  genre: "Acción",
  stock: 16,
  rating: 4.9,
  reviews: 181,
  description: "Kratos continúa su venganza contra los dioses del Olimpo con combates brutales y una escala épica.",
  developer: "Santa Monica Studio",
  releaseYear: 2010,
},
{
  id: 49,
  title: "The Legend of Zelda: Skyward Sword",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 19990,
  originalPrice: 38990,
  discount: 49,
image: "/games/zelda-skyward-sword.jpg",
  genre: "Aventura",
  stock: 13,
  rating: 4.8,
  reviews: 144,
  description: "Acompañá a Link en el origen de la espada maestra en una aventura llena de acertijos, exploración y combates.",
  developer: "Nintendo",
  releaseYear: 2011,
},
{
  id: 50,
  title: "Yakuza 4",
  platform: "Sega",
  platformColor: "#1e4eea",
  price: 14990,
  originalPrice: 28990,
  discount: 48,
image: "/games/yakuza-4.jpg",
  genre: "Acción",
  stock: 19,
  rating: 4.5,
  reviews: 97,
  description: "Controlá a cuatro protagonistas diferentes mientras descubrís una compleja historia criminal en Kamurocho.",
  developer: "Ryu Ga Gotoku Studio",
  releaseYear: 2010,
},
{
  id: 51,
  title: "Cyberpunk 2077",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 32990,
  originalPrice: 59990,
  discount: 45,
  image: "/games/cyberpunk-2077.jpg",
  genre: "RPG",
  stock: 15,
  rating: 4.7,
  reviews: 412,
  description: "RPG de mundo abierto ambientado en Night City, donde las decisiones del jugador influyen en la historia mientras explora un futuro dominado por la tecnología y las corporaciones.",
  developer: "CD Projekt RED",
  releaseYear: 2020,
},

{
  id: 52,
  title: "Hogwarts Legacy",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 34990,
  originalPrice: 59990,
  discount: 42,
  image: "/games/hogwarts-legacy.jpg",
  genre: "Aventura",
  stock: 20,
  rating: 4.8,
  reviews: 368,
  description: "Explorá el Colegio Hogwarts en una aventura de mundo abierto ambientada en el siglo XIX, dominando hechizos, criaturas mágicas y secretos ocultos.",
  developer: "Avalanche Software",
  releaseYear: 2023,
},

{
  id: 53,
  title: "Dead Space",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 31990,
  originalPrice: 55990,
  discount: 43,
  image: "/games/dead-space.jpg",
  genre: "Terror",
  stock: 12,
  rating: 4.8,
  reviews: 221,
  description: "Remake del clásico de terror espacial donde Isaac Clarke debe sobrevivir a los necromorfos a bordo de la nave USG Ishimura.",
  developer: "Motive Studio",
  releaseYear: 2023,
},

{
  id: 54,
  title: "Elden Ring",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 37990,
  originalPrice: 64990,
  discount: 42,
  image: "/games/elden-ring.jpg",
  genre: "RPG",
  stock: 16,
  rating: 5.0,
  reviews: 620,
  description: "Una épica aventura de acción y rol en un inmenso mundo abierto creado por FromSoftware, repleto de desafíos, exploración y combates memorables.",
  developer: "FromSoftware",
  releaseYear: 2022,
},

{
  id: 55,
  title: "EA Sports FC 25",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 41990,
  originalPrice: 69990,
  discount: 40,
  image: "/games/fc-25.jpg",
  genre: "Deportes",
  stock: 25,
  rating: 4.5,
  reviews: 184,
  description: "La nueva entrega del simulador de fútbol de EA Sports, con plantillas actualizadas, nuevos modos de juego y mejoras en la jugabilidad.",
  developer: "EA Sports",
  releaseYear: 2024,
},

{
  id: 56,
  title: "Cuphead",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 14990,
  originalPrice: 24990,
  discount: 40,
  image: "/games/cuphead.jpg",
  genre: "Plataformas",
  stock: 28,
  rating: 4.9,
  reviews: 296,
  description: "Desafiante juego de acción y plataformas inspirado en las caricaturas clásicas de los años 30, famoso por sus intensos combates contra jefes.",
  developer: "Studio MDHR",
  releaseYear: 2017,
},

{
  id: 57,
  title: "Crash Bandicoot N. Sane Trilogy",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 19990,
  originalPrice: 34990,
  discount: 43,
  image: "/games/crash-bandicoot-n-sane-trilogy.jpg",
  genre: "Plataformas",
  stock: 22,
  rating: 4.8,
  reviews: 247,
  description: "La trilogía remasterizada de Crash Bandicoot reúne los tres juegos originales con gráficos renovados y una jugabilidad fiel al clásico.",
  developer: "Vicarious Visions",
  releaseYear: 2017,
},

{
  id: 58,
  title: "DOOM Eternal",
  platform: "Xbox",
  platformColor: "#107c10",
  price: 24990,
  originalPrice: 44990,
  discount: 44,
  image: "/games/doom-eternal.jpg",
  genre: "Acción",
  stock: 19,
  rating: 4.9,
  reviews: 315,
  description: "Shooter en primera persona de ritmo frenético donde el Doom Slayer enfrenta hordas demoníacas con un arsenal devastador.",
  developer: "id Software",
  releaseYear: 2020,
},

{
  id: 59,
  title: "Streets of Rage 4",
  platform: "Sega",
  platformColor: "#1f6bd6",
  price: 15990,
  originalPrice: 29990,
  discount: 47,
  image: "/games/streets-of-rage-4.jpg",
  genre: "Acción",
  stock: 17,
  rating: 4.8,
  reviews: 148,
  description: "El legendario beat 'em up regresa con gráficos dibujados a mano, nuevos personajes y combates cooperativos llenos de nostalgia.",
  developer: "Dotemu",
  releaseYear: 2020,
},

{
  id: 60,
  title: "Chrono Trigger",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 17990,
  originalPrice: 29990,
  discount: 40,
  image: "/games/chrono-trigger.jpg",
  genre: "RPG",
  stock: 14,
  rating: 5.0,
  reviews: 352,
  description: "Considerado uno de los mejores RPG de la historia, ofrece viajes en el tiempo, múltiples finales y un inolvidable sistema de combate.",
  developer: "Square",
  releaseYear: 1995,
},

{
  id: 61,
  title: "Nioh",
  platform: "PlayStation",
  platformColor: "#003791",
  price: 22990,
  originalPrice: 39990,
  discount: 43,
  image: "/games/nioh.jpg",
  genre: "Acción",
  stock: 13,
  rating: 4.7,
  reviews: 188,
  description: "Desafiante RPG de acción ambientado en el Japón feudal, donde samuráis y criaturas sobrenaturales protagonizan intensos combates.",
  developer: "Team Ninja",
  releaseYear: 2017,
},

{
  id: 62,
  title: "Hollow Knight: Silksong",
  platform: "Nintendo",
  platformColor: "#e4000f",
  price: 29990,
  originalPrice: 39990,
  discount: 25,
  image: "/games/hollow-knight-silksong.jpg",
  genre: "Metroidvania",
  stock: 30,
  rating: 5.0,
  reviews: 96,
  description: "Continuación de Hollow Knight protagonizada por Hornet, con nuevos enemigos, habilidades y un extenso reino por descubrir.",
  developer: "Team Cherry",
  releaseYear: 2025,
},
];

export const featuredGames: Game[] = [
  {
    id: 101,
    title: "Elden Ring – Shadow of the Erdtree",
    platform: "PlayStation",
    platformColor: "#003791",
    price: 58990,
    originalPrice: 89990,
    discount: 34,
    image: "https://images.unsplash.com/photo-1533236897111-3e94666b2edf?w=300&h=400&fit=crop&auto=format",
    genre: "RPG",
    stock: 15,
    rating: 4.9,
    reviews: 5200,
    description: "Expansión de Elden Ring con nuevas zonas y desafíos.",
    developer: "FromSoftware",
    releaseYear: 2024,
  },
  {
    id: 102,
    title: "Baldur's Gate 3",
    platform: "Xbox",
    platformColor: "#107c10",
    price: 52990,
    originalPrice: 74990,
    discount: 29,
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=300&h=400&fit=crop&auto=format",
    genre: "RPG",
    stock: 12,
    rating: 4.9,
    reviews: 6100,
    description: "RPG basado en Dungeons & Dragons con decisiones profundas.",
    developer: "Larian Studios",
    releaseYear: 2023,
  },
  {
    id: 103,
    title: "Metroid Prime 4",
    platform: "Nintendo",
    platformColor: "#e4000f",
    price: 48990,
    image: "https://images.unsplash.com/photo-1628278509584-2e14a17e8c23?w=300&h=400&fit=crop&auto=format",
    genre: "Acción",
    stock: 9,
    rating: 4.8,
    reviews: 900,
    description: "Nueva aventura de Samus Aran en primera persona.",
    developer: "Retro Studios",
    releaseYear: 2025,
  },
  {
    id: 104,
    title: "Sonic x Shadow Generations",
    platform: "Sega",
    platformColor: "#1e4eea",
    price: 28990,
    originalPrice: 44990,
    discount: 36,
    image: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=300&h=400&fit=crop&auto=format",
    genre: "Aventura",
    stock: 18,
    rating: 4.6,
    reviews: 1200,
    description: "Sonic y Shadow protagonizan una aventura a gran velocidad.",
    developer: "Sonic Team",
    releaseYear: 2024,
  },
  {
    id: 105,
    title: "WWE 2K26 Standard Edition",
    platform: "PlayStation",
    platformColor: "#003791",
    price: 42005,
    originalPrice: 58340,
    discount: 28,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=300&h=400&fit=crop&auto=format",
    genre: "Deportes",
    stock: 20,
    rating: 4.5,
    reviews: 850,
    description: "La experiencia más completa de lucha libre de WWE.",
    developer: "Visual Concepts",
    releaseYear: 2026,
  },
  {
    id: 106,
    title: "EA Sports FC 26",
    platform: "PlayStation",
    platformColor: "#003791",
    price: 50995,
    originalPrice: 62190,
    discount: 18,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=400&fit=crop&auto=format",
    genre: "Deportes",
    stock: 12,
    rating: 4.4,
    reviews: 2400,
    description: "Fútbol con licencias oficiales y modos competitivos.",
    developer: "EA Sports",
    releaseYear: 2026,
  },
];
